version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
    - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '9090:80'
  app1:
    image: node-app
    environment: 
      - APPID=1111

  app2:
    image: node-app
    environment: 
      - APPID=2222

  app3:
    image: node-app
    environment: 
      - APPID=3333